name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: '16'




