name: CI/CD Pipeline

on:
    push:
        branches:
            - master
        pull_request:
            branches: [master]
            types: [opened, synchronize]

jobs:
    build_pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier
            - name: Build
              run: npm run build
            - name: Build success notification
              uses: slackapi/slack-github-action@v1.19.0
              if: success()
              with:
                  channel-id: "builds"
                  slack-message: "I am a Bot! The build ${{ github.event.pull_request.html_url || github.event.head_commit.url }} was successful."
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            - name: Build failure notification
              uses: slackapi/slack-github-action@v1.19.0
              if: failure()
              with:
                  channel-id: "builds"
                  slack-message: "Oops! The build ${{ github.event.pull_request.html_url || github.event.head_commit.url }} has failed. Please check the logs as soon as possible"
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.2
              with:
                  publish-dir: './build'
                  production-branch: master
                  deploy-message: "Site deployed with Github Actions"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            - name: Deployment success notification
              uses: slackapi/slack-github-action@v1.19.0
              if: success()
              with:
                  channel-id: "deployments"
                  slack-message: "I am a Bot! The deployment at ${{ github.event.pull_request.html_url || github.event.head_commit.url }} was successful."
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            - name: Deployment failure notification
              uses: slackapi/slack-github-action@v1.19.0
              if: failure()
              with:
                  channel-id: "deployments"
                  slack-message: "Oops! The deployment at ${{ github.event.pull_request.html_url || github.event.head_commit.url }} has failed. Please check the logs as soon as possible"
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
