name: CI/CD Pipeline

on:
    push:
        branches:
            - master
        pull_request:
            branches: [master]
            types: [opened, synchronize]

jobs:
    build_pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier
            - name: Build
              run: npm run build
            - name: Success notification to Slack
              uses: slackapi/slack-github-action@v1.19.0
              if: success()
              with:
                  channel-id: "github-actions"
                  slack-message: "I am a Bot! The build ${{ github.event.pull_request.html_url || github.event.head_commit.url }} was successfull."
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            - name: Failure notification to Slack
              uses: slackapi/slack-github-action@v1.19.0
              if: failure()
              with:
                  channel-id: "github-actions"
                  slack-message: "Oops! The build ${{ github.event.pull_request.html_url || github.event.head_commit.url }} has failed. Please check the logs as soon as possible"
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
